import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createMarkdownProcessor, parseFrontmatter } from '@astrojs/markdown-remark';
import remarkSongLanguages from '../src/plugins/remark-song-languages.mjs';

const root = new URL('../', import.meta.url);
const article = new URL('src/content/blog/bangdream-cover-song-list.md', root);
const directory = new URL('public/fonts/song-catalog/', root);
const manifestPath = new URL('manifest.json', directory);
const cssPath = new URL('src/styles/song-catalog-fonts.css', root);
const budget = 300_000;

async function characters() {
  const sets = { sc: new Set(), jp: new Set() };
  const renderer = await createMarkdownProcessor({
    remarkPlugins: [remarkSongLanguages, () => (tree) => {
      function collect(node, language = 'sc') {
        if (node.data?.hProperties?.lang === 'ja') language = 'jp';
        if (node.type === 'text') for (const character of node.value) sets[language].add(character);
        if (node.type === 'html') {
          // The article has download anchors and one Japanese band-name span.
          const target = node.value.includes('lang="ja"') ? 'jp' : language;
          for (const character of node.value.replace(/<[^>]*>/g, '')) sets[target].add(character);
        }
        for (const child of node.children ?? []) collect(child, language);
      }
      collect(tree);
    }],
  });
  await renderer.render(parseFrontmatter(await readFile(article, 'utf8')).content);
  return Object.fromEntries(Object.entries(sets).map(([key, values]) => [key, [...values].sort().join('')]));
}

async function download(url) {
  const response = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' },
    signal: AbortSignal.timeout(60_000),
  });
  if (!response.ok) throw new Error(`Font download failed: ${response.status} (${new URL(url).hostname})`);
  return response;
}

const needed = await characters();
if (process.argv.includes('--check')) {
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  let total = 0;
  for (const language of ['sc', 'jp']) {
    const font = manifest.fonts[language];
    const missing = [...needed[language]].filter((character) => !font.characters.includes(character));
    if (missing.length) throw new Error(`Font ${language} missing characters: ${missing.join('')}. Run npm run fonts:generate.`);
    const data = await readFile(new URL(font.file, directory));
    if (createHash('sha256').update(data).digest('hex') !== font.sha256) throw new Error(`Font ${language} checksum mismatch`);
    total += data.byteLength;
  }
  total += Buffer.byteLength(await readFile(cssPath, 'utf8'));
  if (total > budget) throw new Error(`Font budget exceeded: ${total} > ${budget} bytes`);
  console.log(`Song fonts: coverage OK, ${(total / 1000).toFixed(1)} KB / 300 KB budget (offline check).`);
} else {
  const fonts = {};
  const assets = [];
  let css = '/* Generated by npm run fonts:generate. Self-hosted; no runtime Google requests. */\n';
  for (const [language, family, weight] of [['sc', 'Noto Sans SC', '400..700'], ['jp', 'Noto Sans JP', '400']]) {
    const url = new URL('https://fonts.googleapis.com/css2');
    url.searchParams.set('family', `${family}:wght@${weight}`);
    url.searchParams.set('text', needed[language]);
    url.searchParams.set('display', 'swap');
    const response = await (await download(url)).text();
    const sources = [...response.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\) format\('woff2'\)/g)];
    if (sources.length !== 1) throw new Error(`Expected one WOFF2 subset for ${family}, got ${sources.length}`);
    const data = Buffer.from(await (await download(sources[0][1])).arrayBuffer());
    if (data.subarray(0, 4).toString() !== 'wOF2') throw new Error('Invalid WOFF2 file');
    const sha256 = createHash('sha256').update(data).digest('hex');
    const file = `noto-sans-${language}-${sha256.slice(0, 12)}.woff2`;
    assets.push([file, data]);
    fonts[language] = { file, sha256, bytes: data.byteLength, characters: needed[language] };
    css += response.replaceAll(family, `Catalog Sans ${language.toUpperCase()}`)
      .replace(sources[0][1], `/fonts/song-catalog/${file}`)
      // The subset's own character map handles fallback; avoid a large duplicate range list.
      .replace(/^\s*unicode-range:.*$/gm, '') + '\n';
  }
  const total = assets.reduce((sum, [, data]) => sum + data.byteLength, 0) + Buffer.byteLength(css);
  if (total > budget) throw new Error(`Font budget exceeded: ${total} > ${budget} bytes; nothing written.`);
  // Download license notices before writing the generated assets.
  const licenses = [];
  for (const language of ['sc', 'jp']) {
    const license = await (await download(`https://raw.githubusercontent.com/google/fonts/main/ofl/notosans${language}/OFL.txt`)).text();
    licenses.push([`OFL-${language.toUpperCase()}.txt`, license]);
  }
  await mkdir(directory, { recursive: true });
  for (const [file, data] of [...assets, ...licenses]) await writeFile(new URL(file, directory), data);
  await writeFile(cssPath, css);
  await writeFile(manifestPath, JSON.stringify({ source: 'Google Fonts CSS2 text subsets', fonts }, null, 2) + '\n');
  console.log(`Generated ${assets.length} fonts: ${(total / 1000).toFixed(1)} KB total. ${fileURLToPath(directory)}`);
}
